# application.properties
spring.data.mongodb.uri=mongodb://localhost:27017/warehouse_project_server
spring.data.mongodb.auto-index-creation=true

# JWT settings
jwt.token.secret=mySuperSecureSecretKeyForJWT256bits1234567890
jwt.token.expired=3600000

# Server settings
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.com.nester=DEBUG
logging.level.org.springframework.security=DEBUG